### ISSUE TITLE
Unable to display images

### ISSUE THREAD

**Issue by Doplgangr** [fasiha/fuzzy-anki#18]
Images contained within the cards (i.e. when exporting .apkg, choose "include media") cannot be correctly displayed.

![image](https://cloud.githubusercontent.com/assets/6101532/12445942/43065428-bfa2-11e5-8c8b-2c42b4252ba0.png)

**Comment by fasiha** [comment]
Instead of fixing this one issue, I'd much prefer to rewrite the whole app (this was very much my first big JavaScript project), but that'll take some time. Do you need this fixed quickly? Or are you trying to convert an Anki deck into something printable/readable?

**Comment by Doplgangr** [comment]
I have just found this project today and was amazed at its functionality.

I was looking for some ways to implement a shared anki viewing platform without users actually downloading anki (which is somewhat similar to your original goal).

I went digging into the source and have a solution ready. Please see upcoming pull request! Hope it could help when you're rewriting your project.
