### ISSUE TITLE
Doesn't work anymore. Nothing happens when I upload a local .apkg file

### ISSUE THREAD

**Issue by PraveenMuthu22** [fasiha/fuzzy-anki#20]
Steps to reproduce

Navigate to http://fasiha.github.io/fuzzy-anki/
Click "Choose File"
Select an imported anki deck. (.apkg)
Nothing happens afterwards.

**Comment by fasiha** [comment]
Thank you so much for leaving this note! Looks like it's been broken since January, when a dependency deprecated the external URL I was using 😢. But I fixed it, thanks to you!
