### ISSUE TITLE
This no longer works (need to update to latest version error)

### ISSUE THREAD

**Issue by IllustratedMan-code** [fasiha/fuzzy-anki#21]
![image](https://user-images.githubusercontent.com/60514384/223876949-b2b6b16c-e451-4327-8860-d9dee305023e.png)

This happens no matter what I try.

**Comment by fasiha** [comment]
🥂 nearly ten years with the same SQLite schema 😅 but life moves on! I'll take a look at the new format and handle that. Thanks for the notice!!

**Comment by fasiha** [comment]
By the way @IllustratedMan-code this is almost certainly my fault, not your fault, if you can share your "exam2.apkg", I can make sure it works, but if it's private no problem, I'll find a recent APKG to test.

**Comment by IllustratedMan-code** [comment]
No problem: https://github.com/IllustratedMan-code/Planner/blob/main/Intelligent_Data_Design/cards/exam2.apkg

**Comment by IllustratedMan-code** [comment]
![image](https://user-images.githubusercontent.com/60514384/223879327-a451e922-3c05-465d-8a44-3149867b9cfd.png)
 
Here is my version information as well.

**Comment by fasiha** [comment]
Just pushed a fix, tested with https://github.com/IllustratedMan-code/Planner/blob/main/Intelligent_Data_Design/cards/exam2.apkg and it seems to work:

<img width="917" alt="screenshot of working app" src="https://user-images.githubusercontent.com/37649/223914608-09b518f1-c664-4062-b109-3e6a8f7f5a47.png">

@IllustratedMan-code can you try again? It might take a minute for the CDN to serve you the latest data.
